### ISSUE TITLE
Linux Mint 20 ashmem/binder

### ISSUE THREAD

**Issue by vikrend** [anbox/anbox#1721]
Is there a way to install ashmem/binder on mint 20? Based on ubuntu focal I'm getting 'This PPA does'nt support focal' when trying to add morphis/anbox-support ppa. Also there is no such installed modules already in system.

Result of `sudo modprobe ashmem_linux` (same for binder):
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.9.10-050910-generic

**Comment by johnnybass13** [comment]
I'm new to linux so not sure if this will work but it got mine binder to say it works on ubuntu

- git clone https://github.com/anbox/anbox-modules.git
- cd anbox-modules
- ./install.sh
- sudo modprobe ashmem_linux
- sudo modprobe binder_linux
- and reboot

**Comment by vikrend** [comment]
@johnnybass13 Tried it already. No luck. Here is output:

    master ✔ $ sudo ./INSTALL.sh 
    
    Kernel preparation unnecessary for this kernel.  Skipping...
    
    Building module:
    cleaning build area...
    make -j4 KERNELRELEASE=5.9.10-050910-generic all KERNEL_SRC=/lib/modules/5.9.10-050910-generic/build...(bad exit status: 2)
    Error! Bad return status for module build on kernel: 5.9.10-050910-generic (x86_64)
    Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.
    
    Kernel preparation unnecessary for this kernel.  Skipping...
    
    Building module:
    cleaning build area...
    make -j4 KERNELRELEASE=5.9.10-050910-generic all KERNEL_SRC=/lib/modules/5.9.10-050910-generic/build...(bad exit status: 2)
    Error! Bad return status for module build on kernel: 5.9.10-050910-generic (x86_64)
    Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
    modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.9.10-050910-generic
    modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.9.10-050910-generic
    ls: cannot access '/dev/binder': No such file or directory
    ls: cannot access '/dev/ashmem': No such file or directory

And content of `/var/lib/dkms/anbox-binder/1/build/make.log`:

    DKMS make.log for anbox-binder-1 for kernel 5.9.10-050910-generic (x86_64)
    Sat 09 Jan 2021 04:30:22 PM EET
    make -C /lib/modules/5.9.10-050910-generic/build V=0 M=$PWD
    make[1]: Entering directory '/usr/src/linux-headers-5.9.10-050910-generic'
      AR      /var/lib/dkms/anbox-binder/1/build/built-in.a
      CC [M]  /var/lib/dkms/anbox-binder/1/build/deps.o
      CC [M]  /var/lib/dkms/anbox-binder/1/build/binder.o
    /var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_update_page_range’:
    /var/lib/dkms/anbox-binder/1/build/binder.c:633:19: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
      633 |   down_write(&mm->mmap_sem);
          |                   ^~~~~~~~
          |                   mmap_base
    /var/lib/dkms/anbox-binder/1/build/binder.c:683:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
      683 |   up_write(&mm->mmap_sem);
          |                 ^~~~~~~~
          |                 mmap_base
    /var/lib/dkms/anbox-binder/1/build/binder.c:710:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
      710 |   up_write(&mm->mmap_sem);
          |                 ^~~~~~~~
          |                 mmap_base
    make[2]: *** [scripts/Makefile.build:283: /var/lib/dkms/anbox-binder/1/build/binder.o] Error 1
    make[1]: *** [Makefile:1784: /var/lib/dkms/anbox-binder/1/build] Error 2
    make[1]: Leaving directory '/usr/src/linux-headers-5.9.10-050910-generic'
    make: *** [Makefile:8: all] Error 2

**Comment by sevu** [comment]
The modules cannot be compiled with new kernels anymore. They used something which was locked down for security reasons on the kernel side. It's not a bad thing though, as they are now mainline kernel modules.

You're problem now though is that mint probably does not compile these modules in the kernel. There's just one way, getting a kernel which did compile the two modules. Either you find a PPA of such a kernel somewhere (i.e. someone did already that work) or you compile yourself one.

Albeit … maybe the Linux kernel in Mint has support compiled in? Maybe Linux Mint uses even the same kernel like Ubuntu, which supports this?

In that case, the binder module will use binderfs. You may need to mount it after loading the module (or maybe not if using Snap), see here on how to mount it: https://wiki.archlinux.org/index.php/Anbox#Mounting_binderfs
Also, old versions of Anbox don't know about binderfs, in case you have some old Deb of Anbox.

**Comment by polrus** [comment]
the same problem is valid for Opensuse Tumbleweed - probably for the same reason
@sevu - do you know if this is being worked on to upgrade the code for newer kernel somehow - any bounty found we can donate to for this feature?

**Comment by sevu** [comment]
The code was already upgraded for newer kernels in the sense that it is no longer a third-party kernel module, but an in-tree kernel module.

The problem doesn't lie within the code but in the form of distribution. Some discussion on that is at the end of https://github.com/anbox/anbox-modules/issues/49

To build the modules, one must build the kernel with them, which is less practical as it takes longer. However, it's technically a better way. 3rd-party modules have no guarantees whatsoever to work with the next kernel version (and that's intentional!), while in-tree modules will be adjusted to changes in the kernel. Even in case it would be technically possible, it make no sense to strive to resurrect the modules as 3rd-party modules, as it would need additional manpower to maintain them, which is what this project already lacks the most.

The best way to cover this would be to discuss with openSUSE, whether they build the kernel with
- ashmem as module
- binder as modul OR enabling the binder and binderfs options
(I'm not sure if it's possible to build binder with binderfs into a module)

**Comment by SoulInfernoDE** [comment]
Hey all linux mint folks,
you could try this:
https://github.com/anbox/anbox-modules/issues/75#issuecomment-794079944

I am on linux mint 20.1. You could try to use my .config file but without warranty...
[config.txt](https://github.com/anbox/anbox/files/6144289/config.txt)

Rename the config.txt to .config and put it in the same directory as your downloaded and extracted kernel source.

[I could also provide my already build custom kernel .deb packages but without any warranty....](https://drive.google.com/drive/folders/1X4ojO2KYExc94yc5XFlPx7M_tKu-5gBy?usp=sharing)
..as for now i will build kernels for myself from kernel.org as long as the newer kernels did not have ASHMEM and BINDER
enabled by default.

you can install the .deb packages with: (Again without any warranty. I'm not responsible for whatever you doing)

```
sudo dpkg -i linux-*.deb
```

**Comment by vikrend** [comment]
@SoulInfernoDE Thanks for replying, but i switched to arch last month. So do I close the issue? Seems like the problem is still there.
