### ISSUE TITLE
installation error - binder_linux not found (earlier make errors)

### ISSUE THREAD

**Issue by davary** [anbox/anbox#187]
During the install script (linux mint, amd64)
Bad return status for module build on kernel: 3.13.0-37-generic (amd64)

Here is the make.log file:
DKMS make.log for anbox-modules-ashmem-4~trusty1 for kernel 3.13.0-37-generic (amd64)
Tue Apr 25 19:05:40 MST 2017
make -C /lib/modules/3.13.0-37-generic/build V=0 M=$PWD
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-37-generic'
  LD      /var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/built-in.o
  CC [M]  /var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/deps.o
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/deps.c: In function ‘shmem_zero_setup’:
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/deps.c:9:24: warning: assignment makes pointer from integer without a cast [enabled by default]
   shmem_zero_setup_ptr = kallsyms_lookup_name("shmem_zero_setup");
                        ^
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/deps.c: At top level:
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
  CC [M]  /var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.o
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.c: In function ‘ashmem_read’:
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.c:316:2: error: implicit declaration of function ‘__vfs_read’ [-Werror=implicit-function-declaration]
  ret = __vfs_read(asma->file, buf, len, pos);
  ^
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.c: In function ‘ashmem_shrink_scan’:
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.c:456:3: error: implicit declaration of function ‘vfs_fallocate’ [-Werror=implicit-function-declaration]
   vfs_fallocate(range->asma->file,
   ^
/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.c: At top level:
cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]
cc1: some warnings being treated as errors
make[2]: *** [/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build/ashmem.o] Error 1
make[1]: *** [_module_/var/lib/dkms/anbox-modules-ashmem/4~trusty1/build] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-37-generic'
make: *** [all] Error 2

**Comment by morphis** [comment]
The easiest way to escape from this problem would be to upgrade to a newer kernel. On Ubuntu 14.04 you should be able to do that via the HWE kernel. See https://wiki.ubuntu.com/Kernel/LTSEnablementStack for more details.

**Comment by davary** [comment]
Thanks much, Simon.  Upgrading now.

On 04/26/2017 11:16 AM, Simon Fels wrote:

The easiest way to escape from this problem would be to upgrade to a newer kernel. On Ubuntu 14.04 you should be able to do that via the HWE kernel. See https://wiki.ubuntu.com/Kernel/LTSEnablementStack for more details.

**Comment by davary** [comment]
OK, Still getting this during stall:

Loading new anbox-modules-binder-4~trusty1 DKMS files...
First Installation: checking all kernels...
Building only for 4.8.0-040800-generic
Building for architecture amd64
Building initial module for 4.8.0-040800-generic
Error! Bad return status for module build on kernel: 4.8.0-040800-generic (amd64)
Consult /var/lib/dkms/anbox-modules-binder/4~trusty1/build/make.log for more information.
+ '[' '!' -e /etc/modules-load.d/anbox.conf ']'
+ sudo modprobe binder_linux
modprobe: FATAL: Module binder_linux not found.


and make.log contains:

DKMS make.log for anbox-modules-binder-4~trusty1 for kernel 4.8.0-040800-generic (amd64)
Wed Apr 26 14:55:41 MST 2017
make -C /lib/modules/4.8.0-040800-generic/build V=0 M=$PWD
make[1]: Entering directory `/usr/src/linux-headers-4.8.0-040800-generic'
  LD      /var/lib/dkms/anbox-modules-binder/4~trusty1/build/built-in.o
  CC [M]  /var/lib/dkms/anbox-modules-binder/4~trusty1/build/deps.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
make[2]: *** [/var/lib/dkms/anbox-modules-binder/4~trusty1/build/deps.o] Error 1
make[1]: *** [_module_/var/lib/dkms/anbox-modules-binder/4~trusty1/build] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-4.8.0-040800-generic'
make: *** [all] Error 2


accd to apt-get, I already have the latest version :

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4


I may be too inept to install this.


Dave




On 04/26/2017 02:17 PM, Dave Shreeve wrote:

Thanks much, Simon.  Upgrading now.

On 04/26/2017 11:16 AM, Simon Fels wrote:

The easiest way to escape from this problem would be to upgrade to a newer kernel. On Ubuntu 14.04 you should be able to do that via the HWE kernel. See https://wiki.ubuntu.com/Kernel/LTSEnablementStack for more details.

**Comment by hub2git** [comment]
@davary wrote 

> I may be too inept to install this.

Hang in there. It's still alpha. As the devs work on this, I expect the installation to be easy enough for inept people like you and me. :) (I'm on Mint 18.1 64bit too.)

**Comment by ajahongir** [comment]
having same issue

**Comment by davekr** [comment]
Happens to me as well on Ubuntu 14.04.

**Comment by WuerfelDev** [comment]
same here with Ubuntu 17.04, kernel 4.10
I had it working some time ago, now I uninstalled and tried to install it again to get the newer build but now it didn't work

**Comment by falcucci** [comment]
Any news please? same issue here.

**Comment by falcucci** [comment]
```sudo apt-get remove --purge anbox-modules-dkms```

Uninstall and try to install anbox again.

Works on Ubuntu 14.04 for now.

**Comment by lygstate** [comment]
May this mark as fixed?
