### ISSUE TITLE
Build errors from backtrace-cpp/backward.hpp: switch missing default case / this statement may fall through

### ISSUE THREAD

**Issue by milkmiruku** [anbox/anbox#726]
Trying to build/install via anbox-git in AUR.

```
...
[ 35%] Building CXX object external/backtrace-cpp/CMakeFiles/backward_object.dir/backward.cpp.o
In file included from /var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.cpp:26:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In member function ‘void backward::StackTraceLinuxImplBase::load_thread_info()’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:517:37: warning: use of old-style cast to ‘size_t’ {aka ‘long unsigned int’} [-Wold-style-cast]
   if (_thread_id == (size_t) getpid()) {
                                     ^
                     -----------------
                     static_cast<size_t> ( getpid())
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In static member function ‘static _Unwind_Reason_Code backward::details::Unwinder<F>::backtrace_trampoline(_Unwind_Context*, void*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:576:22: warning: use of old-style cast to ‘class backward::details::Unwinder<F>*’ [-Wold-style-cast]
   return ((Unwinder*)self)->backtrace(ctx);
                      ^~~~
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In member function ‘_Unwind_Reason_Code backward::details::Unwinder<F>::backtrace(_Unwind_Context*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:591:25: warning: use of old-style cast to ‘void*’ [-Wold-style-cast]
    (*_f)(_index, (void*)ip);
                         ^~
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In member function ‘backward::ResolvedTrace backward::TraceResolverLinuxImpl<backward::trace_resolver_tag::libdw>::resolve(backward::ResolvedTrace)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1153:46: warning: use of old-style cast to ‘Dwarf_Addr’ {aka ‘long unsigned int’} [-Wold-style-cast]
   Dwarf_Addr trace_addr = (Dwarf_Addr) trace.addr;
                                              ^~~~
                           -----------------------
                           reinterpret_cast<Dwarf_Addr> ( trace.addr)
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In member function ‘void backward::TraceResolverLinuxImpl<backward::trace_resolver_tag::libdw>::inliners_search_cb::operator()(Dwarf_Die*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1312:11: error: switch missing default case [-Werror=switch-default]
    switch (dwarf_tag(die)) {
           ^
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In member function ‘void backward::Printer::print_source_loc(FILE*, const char*, const backward::ResolvedTrace::SourceLoc&, void*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1852:58: warning: use of old-style cast to ‘int’ [-Wold-style-cast]
     indent, source_loc.filename.c_str(), (int)source_loc.line,
                                                          ^~~~
                                          -----
                                          static_cast<int> (  )
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In constructor ‘backward::SignalHandling::SignalHandling(const std::vector<int>&)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1908:48: warning: use of old-style cast to ‘char*’ [-Wold-style-cast]
   _stack_content.reset((char*)malloc(stack_size));
                                                ^
                        -------
                        static_cast<char*> (     )
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In static member function ‘static void backward::SignalHandling::sig_handler(int, siginfo_t*, void*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1944:36: warning: use of old-style cast to ‘ucontext_t*’ {aka ‘struct ucontext_t ’} [-Wold-style-cast]
   ucontext_t *uctx = (ucontext_t*) _ctx;
                                    ^~~~
                      -
                      static_cast<-
                                  > (   )
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp: In static member function ‘static Dwarf_Die* backward::TraceResolverLinuxImpl<backward::trace_resolver_tag::libdw>::find_fundie_by_pc(Dwarf_Die*, Dwarf_Addr, Dwarf_Die*)’:
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1391:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
      if (die_has_pc(die, pc)) {
      ^~
/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1394:5: note: here
     default:
     ^~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [external/backtrace-cpp/CMakeFiles/backward_object.dir/build.make:63: external/backtrace-cpp/CMakeFiles/backward_object.dir/backward.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1763: external/backtrace-cpp/CMakeFiles/backward_object.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
...
```

**Comment by morphis** [comment]
Looks like the GCC compiler on Arch has a different default set of warnings/errors set than the Ubuntu one or you're user a newer/older one.

Only interesting one from the log above is 

`/var/tmp/trizen-milk/anbox-git/src/anbox/external/backtrace-cpp/backward.hpp:1391:6: error: this statement may fall through [-Werror=implicit-fallthrough=]`

If you want to fix this add `Wno-error=implicit-fallthrough` to https://github.com/anbox/anbox/blob/master/external/backtrace-cpp/CMakeLists.txt#L41

Please provide a PR if that fixes the problem for you.

**Comment by rodarima** [comment]
I've been able to succesfully compile using the following patch using g++ 8.1.0.

By adding `/* FALLTHRU */` as commented [here](https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them). Another compiler errors were fixed by using { } around the case switch, to avoid local variables to be propagated outside. As well as a dummy `default: break;`.

```diff
diff --git a/external/backtrace-cpp/backward.hpp b/external/backtrace-cpp/backward.hpp
index 37be193..6dcecf2 100644
--- a/external/backtrace-cpp/backward.hpp
+++ b/external/backtrace-cpp/backward.hpp
@@ -1311,13 +1311,14 @@ private:
                void operator()(Dwarf_Die* die) {
                        switch (dwarf_tag(die)) {
                                const char* name;
-                               case DW_TAG_subprogram:
+                               case DW_TAG_subprogram: {
                                        if ((name = dwarf_diename(die))) {
                                                trace.source.function = name;
                                        }
                                        break;
+                                       }
 
-                               case DW_TAG_inlined_subroutine:
+                               case DW_TAG_inlined_subroutine: {
                                        ResolvedTrace::SourceLoc sloc;
                                        Dwarf_Attribute attr_mem;
 
@@ -1338,6 +1339,9 @@ private:
 
                                        trace.inliners.push_back(sloc);
                                        break;
+                                       }
+                               default:
+                                       break;
                        };
                }
                ResolvedTrace& trace;
@@ -1391,6 +1395,7 @@ private:
if (die_has_pc(die, pc)) {
                                                return result;
                                        }
+                                       /* FALLTHRU */
                                default:
                                        bool declaration = false;
                                        Dwarf_Attribute attr_mem;
```

**Comment by milkmiruku** [comment]
Thanks @rodarima though I get "error: corrupt patch at line 33", it seems due to tab/space differences. I've tried reindenting with [ctrl-v] tab [in Vim] then gave up and manually edited the file, but I get a slew more errors popping up now (from the same file) so I'll give it another bash in a day or so when I've a clearer head.

**Comment by morphis** [comment]
@rodarima @milkmiruku The right way to get this fixed is to get the patched applied upstream and then introduce the latest backtrace-cpp to Anbox. Until that is done a PR to add `-Wno-error=implicit-fallthrough` is what we should do.

**Comment by rodneyrod** [comment]
I'm still getting this error using the latest pull from master, using the AUR version on Manjaro.

**Comment by HaoZeke** [comment]
Yup the problem persists on the Arch AUR as well.

**Comment by morphis** [comment]
Please see the discussion at https://github.com/anbox/anbox/pull/729#issuecomment-394429861
