### ISSUE TITLE
DKMS Binder Failed Linux Kernel 5.1

### ISSUE THREAD

**Issue by JoshuaDoes** [anbox/anbox#1130]
:heavy_check_mark: 1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
:heavy_check_mark: 2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
:heavy_check_mark: 3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
:heavy_check_mark: 4. Reproduce the error while debug logs enabled.
:heavy_check_mark: 5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

:heavy_check_mark: 
[anbox-system-diagnostics-2019-05-07.zip](https://github.com/anbox/anbox/files/3154388/anbox-system-diagnostics-2019-05-07.zip)
6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
joshuadoes@JoshuaX:~$ anbox system-info
libEGL warning: DRI2: failed to authenticate
version: 4
snap-revision: 173
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Linux Mint
  version: 19.1 (Tessa)
  snap-based: true
kernel:
  version: Linux version 5.1.0-050100-generic (kernel@gloin) (gcc version 8.3.0 (Ubuntu 8.3.0-7ubuntu1)) #201905052130 SMP Mon May 6 01:32:59 UTC 2019
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image_base
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES 3.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
```
</details>

**Please describe your problem:**
After installing the Linux kernel 5.1 on my Linux Mint 19.1 installation (where previously everything worked on the Linux kernel 5.0.9), I noticed a strange error during init where the service `Load Kernel Modules` did not start properly. I proceeded to run the command `systemctl status systemd-modules-load.service` as instructed and noticed that the `ashem` and `binder` kernel modules failed to load.

At this point I had to actually look up what they were as I had forgotten they were used for Anbox, and upon figuring out their use I proceeded to run the commands ``sudo apt purge anbox-modules-dkms` and `sudo apt install anbox-modules-dkms`.

```
joshuadoes@JoshuaX:~$ sudo apt install anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  anbox-modules-dkms
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 38.0 kB of archives.
After this operation, 212 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/morphis/anbox-support/ubuntu bionic/main amd64 anbox-modules-dkms all 13 [38.0 kB]
Fetched 38.0 kB in 1s (62.1 kB/s)             
Selecting previously unselected package anbox-modules-dkms.
(Reading database ... 434254 files and directories currently installed.)
Preparing to unpack .../anbox-modules-dkms_13_all.deb ...
Unpacking anbox-modules-dkms (13) ...
Setting up anbox-modules-dkms (13) ...
Loading new anbox-1 DKMS files...
Building for 5.1.0-050100-generic
Building initial module for 5.1.0-050100-generic
ERROR (dkms apport): kernel package linux-headers-5.1.0-050100-generic is not supported
Error! Bad return status for module build on kernel: 5.1.0-050100-generic (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.
```

And the results of `make.log`:
```
DKMS make.log for anbox-1 for kernel 5.1.0-050100-generic (x86_64)
Tue May  7 16:03:53 EDT 2019
make: Entering directory '/var/lib/dkms/anbox/1/build/ashmem'
make -C /lib/modules/5.1.0-050100-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.1.0-050100-generic'
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.mod.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.1.0-050100-generic'
make: Leaving directory '/var/lib/dkms/anbox/1/build/ashmem'
make: Entering directory '/var/lib/dkms/anbox/1/build/binder'
make -C /lib/modules/5.1.0-050100-generic/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.1.0-050100-generic'
  CC [M]  /var/lib/dkms/anbox/1/build/binder/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/binder/binder.o
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .fault = binder_vm_fault,
           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox/1/build/binder/binder.c:3382:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors
scripts/Makefile.build:275: recipe for target '/var/lib/dkms/anbox/1/build/binder/binder.o' failed
make[2]: *** [/var/lib/dkms/anbox/1/build/binder/binder.o] Error 1
Makefile:1571: recipe for target '_module_/var/lib/dkms/anbox/1/build/binder' failed
make[1]: *** [_module_/var/lib/dkms/anbox/1/build/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.1.0-050100-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/var/lib/dkms/anbox/1/build/binder'
```

I have noticed that this issue exists with previous Linux kernels, including the exact error `error: initialization from incompatible pointer type` in relation to `binder_vm_fault`. I don't wish to proceed with attempting any patches previously made available for Linux kernels such as 4.11 which these issues were made for until I'm given the go-ahead to do something like that.

**What were you expecting?:**
I expected the package `anbox-modules-dkms` to compile and install the kernel module `binder` with success.

**Additional info:**
The sooner I can get this resolved, the saner I'll be about my system :P

**Comment by 86423355844265459587182778** [comment]
@JoshuaDoes 
Please see if anbox/anbox-modules#19 helps.

**Comment by JoshuaDoes** [comment]
It helped to compile the kernel module, but I'm afraid I can't yet modprobe it for some reason:
```
joshuadoes@JoshuaX:~/Projects/anbox-modules$ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Operation not permitted
```

**Comment by 86423355844265459587182778** [comment]
@JoshuaDoes 
Strange. I am on 5.1.1 and is able to modprobe it by `$ sudo modprobe binder_linux`:
```
$ modinfo binder_linux
filename:       /lib/modules/5.1.1-arch1-1-ARCH/extramodules/binder_linux.ko.xz
license:        GPL v2
srcversion:     8FD3FBB38BE74464E55CBA3
depends:        
retpoline:      Y
name:           binder_linux
vermagic:       5.1.1-arch1-1-ARCH SMP preempt mod_unload 
parm:           debug_mask:uint
parm:           proc_no_lock:bool
parm:           num_devices:int
```
```
$ lsmod
Module                  Size  Used by
fuse                  131072  2
intel_rapl             28672  0
intel_powerclamp       20480  0
(...)
iptable_filter         16384  1
vboxnetflt             32768  0
vboxnetadp             28672  0
vboxpci                28672  0
vboxdrv               491520  3 vboxpci,vboxnetadp,vboxnetflt
sg                     40960  0
crypto_user            16384  0
binder_linux          118784  0
ashmem_linux           16384  0
ip_tables              32768  12 iptable_filter,iptable_nat
x_tables               49152  18 ip6table_filter,xt_conntrack,iptable_filter,xt_LOG,xt_multiport,ip6t_MASQUERADE,xt_tcpudp,xt_tcpmss,ipt_MASQUERADE,xt_addrtype,ip6t_rt,ip6_tables,ipt_REJECT,ip_tables,xt_limit,xt_hl,ip6table_mangle,ip6t_REJECT
(...)
```

**Comment by JoshuaDoes** [comment]
I'm still on 5.1 so I'll try upgrading to 5.1.1 and see if even the slight difference makes it work
```
joshuadoes@JoshuaX:~$ modinfo binder_linux
filename:       /lib/modules/5.1.0-050100-generic/updates/binder_linux.ko
license:        GPL v2
srcversion:     8FD3FBB38BE74464E55CBA3
depends:        
retpoline:      Y
name:           binder_linux
vermagic:       5.1.0-050100-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
parm:           debug_mask:uint
parm:           proc_no_lock:bool
parm:           num_devices:int
joshuadoes@JoshuaX:~$ sudo modprobe binder_linux
modprobe: ERROR: could not insert 'binder_linux': Operation not permitted
```

**Comment by JoshuaDoes** [comment]
Aha, found the issue!

Looks like the kernel module needed to be signed with a key for secure boot (even though I have secure boot disabled?), just followed [this gist](https://gist.github.com/dop3j0e/2a9e2dddca982c4f679552fc1ebb18df) and it worked like a charm

**Comment by lilianmoraru** [comment]
Linux Kernel 5.1.3, can confirm that the fix works.

**Comment by jdines** [comment]
Apparently nobody tried to reboot first?  Almost certainly the reason your code signing approach worked is that there is a step in that process where you reboot the system.  Simply reboot and the binder_linux module loads fine at least for kernel 5.0.17-300.fc30.x86_64. I'd be *really* surprised if it wasn't true for the other versions as well.  There is, as you said, no reason to believe that the module needs to be signed with secure boot disabled. Note that ashmem_linux loads fine without signing for example.

**Comment by JoshuaDoes** [comment]
@jdines I'm afraid to tell you but I rebooted quite a few times, one of them being to upgrade to Linux 5.1.1. Maybe there's some unknown changes that have been made in one of the two

**Comment by jdines** [comment]
@JoshuaDoes ... Don't be afraid buddy. Everything is going to be alright!

What distribution are you using? (cat /etc/os-release)

The one thing we know for sure is that signing modules isn't required or, as I said, ashmem wouldn't load successfully. I haven't looked carefully at the scripts in the link you provided but they may be changing something about the system not related to signing as well.

**Comment by JoshuaDoes** [comment]
Linux Mint 19.1, hijacked with Bedrock Linux 0.7.6 however Anbox has worked fine previously with this setup - the only change made was the Linux kernel version.

The root of the issue seems to be something that was changed in the kernel, as previously the `anbox-modules-dkms` package would install just fine and load both modules just fine (although I'd reboot after as the install guide instructed), but in this case it failed to even try loading the module unless it was signed despite me having secure boot disabled.

Is there any particular reason that you know of as for why ashmem can load without rebooting but binder requires a reboot before being loaded? Whatever changed to this particular reason is why the package gives an error now on install

**Comment by jdines** [comment]
I would have to look at the source in order to be sure, but I do know ashmem just adds a different shared memory scheme whereas binder adds the ability to bind to various hardware devices and adds a new filesystem called binderfs.

Have you tried to go back to boot the older kernel since it has been working? This would help isolate if it really is a kernel/binder compatibility issue or something else that has changed with your system.

**Comment by JoshuaDoes** [comment]
I haven't gone back to look as the situation is personally resolved for me. I can try and rebuild the source, install, reboot, and then modprobe it without signing it sometime tomorrow while I'm at work to see if it works that way now, as it didn't want to cooperate almost a month ago. I'll attempt it on Linux 4.20 where I didn't have this issue and then I'll try it again on Linux 5.1 where I did have this issue

**Comment by josephworks** [comment]
nope, I am using Linux 5.3.0-13 and it is still broken

**Comment by jershell** [comment]
Linux XPS-15-9575 5.1.16-050116-generic #201907031232 SMP Wed Jul 3 12:35:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Not working

**Comment by aplatypus** [comment]
Using Ubuntu 19.04, kernel 5.0.7

Reviewing the above comments, it looks like Anbox has a dependency on a more recent kernel verison.  Is that understanding correct?

Oh and not using secure boot.  Really not intersted in using secure boot to be truthful.

**Comment by yasuoohno** [comment]
Hi, I'm using Ubuntu 18.04 and kernel 5.3.0-26 and had same error.
I patched binder.c as following and it seems working well.

$ sudo modprobe binder_linux
$ sudo modprobe ashmem_linux
$ lsmod | grep _linux
ashmem_linux           20480  6
binder_linux          159744  33
yasuo@m715q:/usr/src/anbox-1/binder$ uname -a
Linux m715q 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

--- binder.c.bak        2020-01-25 12:22:04.407802416 +0900
+++ binder.c    2020-01-25 12:07:50.435879967 +0900
@@ -3368,7 +3368,11 @@
 }
 
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)
+#  if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 17, 0)
+static vm_fault_t binder_vm_fault(struct vm_fault *vmf)
+#  else
 static int binder_vm_fault(struct vm_fault *vmf)
+#  endif
 #else
 static int binder_vm_fault(struct vm_area_struct *vma, struct vm_fault *vmf)
 #endif

**Comment by josephworks** [comment]
That's great, but let's say I try to install Anbox to Ubuntu using Linux v5, will it work? If not, then the issue still exists...

**Comment by JoshuaDoes** [comment]
@josephworks The patch by @yasuoohno would allow it to install on Linux 5.x with no issue so long as the kernel doesn't have any module breaking changes

**Comment by josephworks** [comment]
Ok, that's great! Buy, what I am trying to say is that if I install Anbox to a new Ubuntu Install, then it should work without me needing to look for and use a patch.

**Comment by JoshuaDoes** [comment]
I completely agree, maybe we can get this into the repo soon so a later build will ship with it

**Comment by josephworks** [comment]
Is this still an issue?

**Comment by JoshuaDoes** [comment]
So long as the forced fault due to a newer Linux kernel version is in place, it will persistently become an issue. My recommended course of action would instead be to use a minimum version number for the version of Linux with the compatible APIs you're using, and when an API breaking change is introduced in a new Linux version simply bump the minimum version number to that new version and make a new release

**Comment by josephworks** [comment]
[**@stale**](https://github.comhttps://github.com/marketplace/stale) commented on [Sep 27, 2020, 5:49 AM MST](https://github.com/anbox/anbox/issues/1130#issuecomment-699631345 "2020-09-27T12:49:24Z - Replied by Github Reply Comments"):
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

That's great, but has it been fixed yet?

**Comment by aliquo93** [comment]
Hi to all, I can't understand how to patch binder.c like yasuoohno said. What I have to do after "uname-a" command?

**Comment by aliquo93** [comment]
Hi to all, I can't understand how to patch binder.c like yasuoohno said. What I have to do after "uname-a" command?

@yasuoohno Could you please help me?

**Comment by mhogerheijde** [comment]
@aliquo93 The patch is outdated, unfortunately. 

But for completeness, you would apply the patch by:

(0. cloning this repository)
1. saving the content of the patch (starting from `--- binder.c.bak ...` to `#endif`) in a file of you choosing. (Let's assume `~/anbox-binder.patch`
2. use the `patch` command to apply it: `patch path/to/anbox-modules/binder/binder.c < ~/anbox-binder.patch`

If you do so now, `patch` will complain that the patch is invalid, since `binder.c` was changed and this patch cannot cleanly apply anymore.

**Comment by josephworks** [comment]
Wow! It's been 2 years already?!
Anyways, Ill test this on fresh Ubuntu 20.04, but I doubt the issue is fixed.

**Comment by Peng1029** [comment]
yeah still a problem on ubuntu 21.04

**Comment by fsevenm** [comment]
> yeah still a problem on ubuntu 21.04

Same here, please help!

**Comment by Fuseteam** [comment]
pretty sure you don't need to use DKMS binder on ubuntu anymore, it is shipped by the default kernel now

**Comment by fsevenm** [comment]
> pretty sure you don't need to use DKMS binder on ubuntu anymore, it is shipped by the default kernel now

Correct, just disable secure boot, then it just works. Anyways, binder changed to binderfs in my case and it's already shipped with the kernel.

**Comment by Fuseteam** [comment]
@fsevenm _pretty_ sure binder works with secure boot, tis just ashmem that's being picky about secure boot

**Comment by fsevenm** [comment]
Ah yes, that's what I meant. I was thinking of the whole anbox when I wrote that, disabling secure boot for ashmen thing. 😅

**Comment by Peng1029** [comment]
I never had secure boot on, its been off for around a year

**Comment by Fuseteam** [comment]
yeah secure boot is only an issue with ashmem not with binder

**Comment by fsevenm** [comment]
@Peng1029 have you tried this? From https://github.com/anbox/anbox/blob/master/docs/install.md, 

>In Ubuntu 19.10 the binder driver doesn't create /dev/binder when loaded. That is intentional. Instead it provides support with binderfs (see https://brauner.github.io/2019/01/09/android-binderfs.html) which is instead since PR anbox/anbox#1309

>You can use grep binder `/proc/filesystems || echo "binderfs support is missing"` To check for binderfs support. Note that only the snap supports binderfs without manual intervention as of now (PR welcome).

In my machine, it's binderfs as mentioned. But, as of now, only the snap version can work with it naturally. I've never tried anbox non-snap version yet, tho.

**Comment by Peng1029** [comment]
I get nodev binder as output and in the snap version it still say missing binder

**Comment by Fuseteam** [comment]
> I get nodev binder as output and in the snap version it still say missing binder

the nodev is correct that means it is loaded
can you post the full output of `anbox session-manager` and `anbox system-info`?

**Comment by Peng1029** [comment]
anbox system-info
version: 4
snap-revision: 186
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 21.04 (Hirsute Hippo)
  snap-based: true
kernel:
  version: Linux version 5.11.0-31-generic (buildd@lcy01-amd64-009) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array




anbox session-manager
nothing at all

**Comment by Fuseteam** [comment]
if anbox session-manager appears to hang, then it is working correctly, leave that running and launch anbox normally
if that works set the environment correctly in the desktop file as explained in #1854

**Comment by josephworks** [comment]
Still and issue on 21.10

**Comment by Fuseteam** [comment]
@josephworks you don't even need dkms binder on 21.10

**Comment by josephworks** [comment]
I'll give it another try.

**Comment by josephworks** [comment]
Update: Ashmen is installed, but binder isn't.
Anbox would freeze on the "Starting..." screen.

@Fuseteam what makes you think that I don't need binder on 21.10?

**Comment by Fuseteam** [comment]
Well @josephworks that's because binder has been part of the ubuntu kernel since 19.10 :p 
That behavior does sound familiar tho, what does `anbox session-manager` say?

**Comment by josephworks** [comment]
> ls /dev/binder
ls: cannot access '/dev/binder': No such file or directory

Also, here is the output of ``anbox session-manager``
`(base) joseph@DESKTOP-JOSEPH-Ubuntu:~$ cat out.txt                                                                      Failed to open libEGL.so.1: [/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)]                                                                                                   [ 2022-04-20 06:41:09] [daemon.cpp:61@Run] Failed to initialize OpenGL renderer`

**Comment by Fuseteam** [comment]
aaaand there's the real issue, that's #1939

yes you can ignore /dev/binder missing, that hasn't worked like that since ubuntu 19.10 or even ubuntu 19.04
